import logger from "@mks2508/better-logger";

const hlsLog = logger.component("HLSService");

/**
 * Service for serving HLS content (fMP4 + m3u8) from transmux output
 *
 * Serves the playlist and stream files generated by TransmuxCore CLI
 * from /tmp/mks-iptv-transmux-<sessionId>/ directories.
 *
 * @example
 * ```typescript
 * const service = new HLSService();
 * const playlist = await service.getPlaylist("abc123");
 * const stream = await service.getStream("abc123", "bytes=0-1000");
 * ```
 */
export class HLSService {
  private readonly BASE_DIR = "/tmp";

  /**
   * Get the HLS playlist (m3u8) for a given session
   *
   * Reads the stream.m3u8 file from the session output directory.
   *
   * @param sessionId - Transmux session ID
   * @returns Playlist text content or null if not found
   */
  async getPlaylist(sessionId: string): Promise<string | null> {
    const path = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}/stream.m3u8`;

    try {
      const file = Bun.file(path);
      const exists = await file.exists();

      if (!exists) {
        hlsLog.warn(`Playlist not found: ${path}`);
        return null;
      }

      const text = await file.text();
      hlsLog.info(`Served playlist for session ${sessionId} (${text.length} bytes)`);
      return text;
    } catch (error) {
      hlsLog.error(
        `Failed to read playlist: ${error instanceof Error ? error.message : String(error)}`
      );
      return null;
    }
  }

  /**
   * Get the stream file (fMP4) for a given session with optional Range support
   *
   * Supports HTTP Range requests (206 Partial Content) for efficient
   * video streaming. Falls back to full file (200) when no Range header.
   *
   * @param sessionId - Transmux session ID
   * @param rangeHeader - Optional HTTP Range header value
   * @returns Object with file data, status code, and headers
   */
  async getStream(
    sessionId: string,
    rangeHeader?: string | null
  ): Promise<{
    body: Blob | null;
    status: number;
    headers: Record<string, string>;
  }> {
    const path = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}/stream.mp4`;

    try {
      const file = Bun.file(path);
      const exists = await file.exists();

      if (!exists) {
        hlsLog.warn(`Stream file not found: ${path}`);
        return {
          body: null,
          status: 404,
          headers: { "Content-Type": "application/json" },
        };
      }

      const fileSize = file.size;

      // Handle Range request
      if (rangeHeader) {
        const match = rangeHeader.match(/bytes=(\d+)-(\d*)/);
        if (match) {
          const start = parseInt(match[1], 10);
          const end = match[2] ? parseInt(match[2], 10) : fileSize - 1;
          const chunkSize = end - start + 1;

          hlsLog.info(`Range request: ${start}-${end}/${fileSize} (${chunkSize} bytes)`);

          const slice = file.slice(start, end + 1);

          return {
            body: slice,
            status: 206,
            headers: {
              "Content-Type": "video/mp4",
              "Content-Length": String(chunkSize),
              "Content-Range": `bytes ${start}-${end}/${fileSize}`,
              "Accept-Ranges": "bytes",
            },
          };
        }
      }

      // Full file response
      hlsLog.info(`Full stream response for session ${sessionId} (${fileSize} bytes)`);

      return {
        body: file,
        status: 200,
        headers: {
          "Content-Type": "video/mp4",
          "Content-Length": String(fileSize),
          "Accept-Ranges": "bytes",
        },
      };
    } catch (error) {
      hlsLog.error(
        `Failed to serve stream: ${error instanceof Error ? error.message : String(error)}`
      );
      return {
        body: null,
        status: 500,
        headers: { "Content-Type": "application/json" },
      };
    }
  }
}
