import { tmpdir } from "node:os";
import logger from "@mks2508/better-logger";
import type { CLIService } from "../cli/service";
import type { ISegmentInfo } from "./model";
import { SegmentScanner } from "./scanner";

const hlsLog = logger.component("HLSService");

/**
 * Service for serving HLS content (fMP4 + m3u8) from transmux output
 *
 * Serves the playlist and stream files generated by TransmuxCore CLI
 * from /tmp/mks-iptv-transmux-<sessionId>/ directories.
 *
 * Includes live BYTERANGE playlist generation for progressive HLS.js playback
 * and segment info for frontend progress visualization.
 *
 * @example
 * ```typescript
 * const service = new HLSService(cliService);
 * const playlist = await service.getPlaylist("abc123");
 * const stream = await service.getStream("abc123", "bytes=0-1000");
 * const live = await service.getLivePlaylist("abc123");
 * const info = await service.getSegmentInfo("abc123");
 * ```
 */
export class HLSService {
  private readonly BASE_DIR = tmpdir();
  private readonly scanner = new SegmentScanner();
  private cliService: CLIService | null = null;

  /**
   * Inject the CLIService reference for accessing session metadata
   *
   * Called during Elysia module setup to avoid circular dependency.
   *
   * @param cli - The CLIService instance
   */
  setCLIService(cli: CLIService): void {
    this.cliService = cli;
  }

  /**
   * Get the HLS playlist (m3u8) for a given session
   *
   * Reads the stream.m3u8 file from the session output directory.
   *
   * @param sessionId - Transmux session ID
   * @returns Playlist text content or null if not found
   */
  async getPlaylist(sessionId: string): Promise<string | null> {
    const path = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}/stream.m3u8`;

    try {
      const file = Bun.file(path);
      const exists = await file.exists();

      if (!exists) {
        hlsLog.warn(`Playlist not found: ${path}`);
        return null;
      }

      const text = await file.text();
      hlsLog.info(`Served playlist for session ${sessionId} (${text.length} bytes)`);
      return text;
    } catch (error) {
      hlsLog.error(
        `Failed to read playlist: ${error instanceof Error ? error.message : String(error)}`
      );
      return null;
    }
  }

  /**
   * Generate a live BYTERANGE EVENT playlist from scanned stream.mp4 segments
   *
   * Produces an HLS v7 playlist where each segment is a BYTERANGE into the
   * single stream.mp4 file. Uses EVENT playlist type so HLS.js periodically
   * reloads to discover new segments as the file grows.
   *
   * The playlist omits #EXT-X-ENDLIST while the session is running,
   * causing HLS.js to reload at its configured interval.
   *
   * @param sessionId - Transmux session ID
   * @returns Playlist text or null if stream not ready
   */
  async getLivePlaylist(sessionId: string): Promise<string | null> {
    const outputDir = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}`;
    const { segments, initSize, timescale } = await this.scanner.scan(sessionId, outputDir);

    if (segments.length === 0 || initSize === 0) {
      hlsLog.warn(`No segments found for live playlist: ${sessionId}`);
      return null;
    }

    // Determine session status for ENDLIST decision
    const session = this.getSessionById(sessionId);
    const isComplete = session
      ? session.status === "completed" || session.status === "failed" || session.status === "killed"
      : false;

    // Compute max segment duration for TARGETDURATION
    let maxDuration = 0;
    for (const seg of segments) {
      const segDur = seg.durationTicks / timescale;
      if (segDur > maxDuration) maxDuration = segDur;
    }
    const targetDuration = Math.ceil(maxDuration || 6);

    // Build playlist
    const lines: string[] = [
      "#EXTM3U",
      "#EXT-X-VERSION:7",
      `#EXT-X-TARGETDURATION:${targetDuration}`,
      "#EXT-X-PLAYLIST-TYPE:EVENT",
      `#EXT-X-MAP:URI="stream.mp4",BYTERANGE="${initSize}@0"`,
      "",
    ];

    for (const seg of segments) {
      const duration = (seg.durationTicks / timescale).toFixed(3);
      lines.push(`#EXTINF:${duration},`);
      lines.push(`#EXT-X-BYTERANGE:${seg.byteLength}@${seg.byteOffset}`);
      lines.push("stream.mp4");
      lines.push("");
    }

    if (isComplete) {
      lines.push("#EXT-X-ENDLIST");
    }

    const playlist = lines.join("\n");
    hlsLog.info(
      `Live playlist: ${segments.length} segs, targetDur=${targetDuration}, complete=${isComplete}`
    );

    return playlist;
  }

  /**
   * Get segment info metadata for a session
   *
   * Returns progress information for the frontend to build the progress bar:
   * total duration, available duration, segment counts, and session status.
   *
   * @param sessionId - Transmux session ID
   * @returns Segment info or null if session not found
   */
  async getSegmentInfo(sessionId: string): Promise<ISegmentInfo | null> {
    const session = this.getSessionById(sessionId);
    if (!session) {
      hlsLog.warn(`Session not found for info: ${sessionId}`);
      return null;
    }

    const outputDir = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}`;
    const { segments, initSize, timescale } = await this.scanner.scan(sessionId, outputDir);

    // Calculate available duration from scanned segments
    let availableDuration = 0;
    for (const seg of segments) {
      availableDuration += seg.durationTicks / timescale;
    }

    // Total duration from CLI session metadata
    const totalDuration = session.duration || 0;

    // Estimate total segments
    const avgSegDuration = segments.length > 0 ? availableDuration / segments.length : 4;
    const totalSegments = totalDuration > 0 ? Math.ceil(totalDuration / avgSegDuration) : 0;

    return {
      totalDuration,
      availableDuration: Math.round(availableDuration * 10) / 10,
      segmentCount: segments.length,
      totalSegments,
      status: session.status,
      initSegmentSize: initSize || session.initSegmentSize,
      timescale,
    };
  }

  /**
   * Look up a session by ID from the CLI service
   *
   * @param sessionId - Session ID to find
   * @returns Session object or null
   */
  private getSessionById(sessionId: string) {
    if (!this.cliService) return null;
    const { sessions } = this.cliService.getSessions();
    return sessions.find((s) => s.sessionId === sessionId) ?? null;
  }

  /**
   * Get the stream file (fMP4) for a given session with optional Range support
   *
   * Supports HTTP Range requests (206 Partial Content) for efficient
   * video streaming. Falls back to full file (200) when no Range header.
   *
   * @param sessionId - Transmux session ID
   * @param rangeHeader - Optional HTTP Range header value
   * @returns Object with file data, status code, and headers
   */
  async getStream(
    sessionId: string,
    rangeHeader?: string | null
  ): Promise<{
    body: Blob | null;
    status: number;
    headers: Record<string, string>;
  }> {
    const path = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}/stream.mp4`;

    try {
      const file = Bun.file(path);
      const exists = await file.exists();

      if (!exists) {
        hlsLog.warn(`Stream file not found: ${path}`);
        return {
          body: null,
          status: 404,
          headers: { "Content-Type": "application/json" },
        };
      }

      const fileSize = file.size;

      // Handle Range request
      if (rangeHeader) {
        const match = rangeHeader.match(/bytes=(\d+)-(\d*)/);
        if (match) {
          const start = parseInt(match[1], 10);
          const end = match[2] ? parseInt(match[2], 10) : fileSize - 1;

          // Validate range bounds
          if (start >= fileSize || start > end || end >= fileSize) {
            hlsLog.warn(
              `Invalid range: ${start}-${end}/${fileSize}`
            );
            return {
              body: null,
              status: 416,
              headers: {
                "Content-Range": `bytes */${fileSize}`,
                "Accept-Ranges": "bytes",
              },
            };
          }

          const chunkSize = end - start + 1;

          hlsLog.info(`Range request: ${start}-${end}/${fileSize} (${chunkSize} bytes)`);

          const slice = file.slice(start, end + 1);

          return {
            body: slice,
            status: 206,
            headers: {
              "Content-Type": "video/mp4",
              "Content-Length": String(chunkSize),
              "Content-Range": `bytes ${start}-${end}/${fileSize}`,
              "Accept-Ranges": "bytes",
            },
          };
        }
      }

      // Full file response
      hlsLog.info(`Full stream response for session ${sessionId} (${fileSize} bytes)`);

      return {
        body: file,
        status: 200,
        headers: {
          "Content-Type": "video/mp4",
          "Content-Length": String(fileSize),
          "Accept-Ranges": "bytes",
        },
      };
    } catch (error) {
      hlsLog.error(
        `Failed to serve stream: ${error instanceof Error ? error.message : String(error)}`
      );
      return {
        body: null,
        status: 500,
        headers: { "Content-Type": "application/json" },
      };
    }
  }

  /**
   * Serve any file from a session's output directory
   *
   * Used by HLS.js to fetch init segments (init.mp4) and media segments
   * (seg_XXX.mp4) referenced by the m3u8 playlist.
   *
   * @param sessionId - Transmux session ID
   * @param filename - File name within the session directory
   * @param rangeHeader - Optional HTTP Range header value
   * @returns Object with file data, status code, and headers
   */
  async getSessionFile(
    sessionId: string,
    filename: string,
    rangeHeader?: string | null
  ): Promise<{
    body: Blob | null;
    status: number;
    headers: Record<string, string>;
  }> {
    // Sanitize filename — only allow alphanumeric, underscore, dash, dot
    if (!/^[\w\-.]+$/.test(filename)) {
      hlsLog.warn(`Invalid filename requested: ${filename}`);
      return {
        body: null,
        status: 400,
        headers: { "Content-Type": "application/json" },
      };
    }

    const path = `${this.BASE_DIR}/mks-iptv-transmux-${sessionId}/${filename}`;

    try {
      const file = Bun.file(path);
      const exists = await file.exists();

      if (!exists) {
        hlsLog.warn(`Session file not found: ${path}`);
        return {
          body: null,
          status: 404,
          headers: { "Content-Type": "application/json" },
        };
      }

      const fileSize = file.size;
      const contentType = filename.endsWith(".mp4")
        ? "video/mp4"
        : filename.endsWith(".m3u8")
          ? "application/vnd.apple.mpegurl"
          : "application/octet-stream";

      // Handle Range request
      if (rangeHeader) {
        const match = rangeHeader.match(/bytes=(\d+)-(\d*)/);
        if (match) {
          const start = parseInt(match[1], 10);
          const end = match[2] ? parseInt(match[2], 10) : fileSize - 1;

          if (start >= fileSize || start > end || end >= fileSize) {
            return {
              body: null,
              status: 416,
              headers: {
                "Content-Range": `bytes */${fileSize}`,
                "Accept-Ranges": "bytes",
              },
            };
          }

          const chunkSize = end - start + 1;
          return {
            body: file.slice(start, end + 1),
            status: 206,
            headers: {
              "Content-Type": contentType,
              "Content-Length": String(chunkSize),
              "Content-Range": `bytes ${start}-${end}/${fileSize}`,
              "Accept-Ranges": "bytes",
            },
          };
        }
      }

      hlsLog.info(`Served ${filename} for session ${sessionId} (${fileSize} bytes)`);
      return {
        body: file,
        status: 200,
        headers: {
          "Content-Type": contentType,
          "Content-Length": String(fileSize),
          "Accept-Ranges": "bytes",
        },
      };
    } catch (error) {
      hlsLog.error(
        `Failed to serve session file: ${error instanceof Error ? error.message : String(error)}`
      );
      return {
        body: null,
        status: 500,
        headers: { "Content-Type": "application/json" },
      };
    }
  }
}
