import Hls from "hls.js";
import { useCallback, useEffect, useRef, useState } from "react";

/** Resolve API base URL for stream endpoints */
const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:3000";

/**
 * Segment info from the backend /hls/:id/info endpoint
 */
interface ISegmentInfo {
  totalDuration: number;
  availableDuration: number;
  segmentCount: number;
  totalSegments: number;
  status: string;
  initSegmentSize: number;
  timescale: number;
}

/**
 * State exposed by the HLS player hook
 */
export interface IHLSPlayerState {
  /** Ref to attach to the <video> element */
  videoRef: React.RefObject<HTMLVideoElement | null>;
  /** Whether HLS.js has parsed the manifest and started playing */
  loaded: boolean;
  /** Error message (null when healthy) */
  error: string | null;
  /** Whether the video is currently playing */
  playing: boolean;
  /** Current playback time in seconds */
  currentTime: number;
  /** Total source duration in seconds (from session metadata) */
  totalDuration: number;
  /** Duration of content available in stream.mp4 so far */
  availableDuration: number;
  /** Number of fMP4 segments scanned */
  segmentCount: number;
  /** Session status: running, completed, failed, killed */
  sessionStatus: string;
  /** Seek within available range (native HLS.js seek) */
  seekTo: (time: number) => void;
  /** Toggle play/pause */
  togglePlay: () => void;
}

/**
 * Hook for progressive HLS playback using HLS.js
 *
 * Loads a BYTERANGE EVENT playlist (live.m3u8) generated by the backend
 * from scanning stream.mp4 moof/mdat boundaries. HLS.js periodically
 * reloads the playlist to discover new segments as the file grows.
 *
 * Polls `/hls/:id/info` every 2s while session is running to update
 * available duration for the progress bar.
 *
 * @param sessionId - Active transmux session ID (null = no source)
 * @returns Player state and control functions
 */
export function useHLSPlayer(sessionId: string | null): IHLSPlayerState {
  const videoRef = useRef<HTMLVideoElement>(null);
  const hlsRef = useRef<Hls | null>(null);
  const infoTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [playing, setPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [totalDuration, setTotalDuration] = useState(0);
  const [availableDuration, setAvailableDuration] = useState(0);
  const [segmentCount, setSegmentCount] = useState(0);
  const [sessionStatus, setSessionStatus] = useState("running");

  /**
   * Fetch segment info from the backend
   */
  const fetchInfo = useCallback(
    async (sid: string) => {
      try {
        const res = await fetch(`${API_BASE}/hls/${sid}/info`);
        if (!res.ok) return;
        const info: ISegmentInfo = await res.json();
        setTotalDuration(info.totalDuration);
        setAvailableDuration(info.availableDuration);
        setSegmentCount(info.segmentCount);
        setSessionStatus(info.status);
      } catch {
        // Silently ignore poll failures
      }
    },
    []
  );

  /**
   * Initialize HLS.js and start playback
   */
  useEffect(() => {
    if (!sessionId) {
      // Cleanup when session clears
      cleanup();
      setLoaded(false);
      setError(null);
      setPlaying(false);
      setCurrentTime(0);
      setTotalDuration(0);
      setAvailableDuration(0);
      setSegmentCount(0);
      setSessionStatus("running");
      return;
    }

    const video = videoRef.current;
    if (!video) return;

    // Reset state
    setError(null);
    setLoaded(false);

    const playlistUrl = `${API_BASE}/hls/${sessionId}/live.m3u8`;

    if (Hls.isSupported()) {
      const hls = new Hls({
        // EVENT playlist — reload to discover new segments
        liveSyncDurationCount: 2,
        liveMaxLatencyDurationCount: 5,
        maxBufferLength: 30,
        maxMaxBufferLength: 60,
        // Faster manifest reloads while stream is growing
        manifestLoadingMaxRetry: 10,
        manifestLoadingRetryDelay: 1000,
        levelLoadingMaxRetry: 10,
        levelLoadingRetryDelay: 1000,
        // Fragment loading
        fragLoadingMaxRetry: 6,
        fragLoadingRetryDelay: 500,
        // Don't start playback at the live edge — start from beginning
        liveDurationInfinity: false,
        // Start at position 0
        startPosition: 0,
      });

      hls.loadSource(playlistUrl);
      hls.attachMedia(video);

      hls.on(Hls.Events.MANIFEST_PARSED, () => {
        setLoaded(true);
        video.play().catch(() => {
          // Autoplay may be blocked by browser policy
        });
      });

      hls.on(Hls.Events.ERROR, (_event, data) => {
        // Audio codec errors are expected (EAC3 not supported in browsers)
        if (data.details === "fragParsingError" || data.details === "bufferAppendError") {
          // Non-fatal codec issues — show warning but don't kill playback
          if (data.fatal) {
            hls.recoverMediaError();
          }
          return;
        }

        if (data.fatal) {
          switch (data.type) {
            case Hls.ErrorTypes.NETWORK_ERROR:
              // Manifest not ready yet — retry
              if (data.details === "manifestLoadError" || data.details === "levelLoadError") {
                setTimeout(() => hls.loadSource(playlistUrl), 2000);
                return;
              }
              setError(`Network error: ${data.details}`);
              hls.startLoad();
              break;
            case Hls.ErrorTypes.MEDIA_ERROR:
              setError(`Media error: ${data.details}`);
              hls.recoverMediaError();
              break;
            default:
              setError(`Fatal error: ${data.details}`);
              break;
          }
        }
      });

      hlsRef.current = hls;
    } else if (video.canPlayType("application/vnd.apple.mpegurl")) {
      // Native HLS support (Safari)
      video.src = playlistUrl;
      video.addEventListener(
        "loadedmetadata",
        () => {
          setLoaded(true);
          video.play().catch(() => {});
        },
        { once: true }
      );
    } else {
      setError("HLS playback not supported in this browser");
    }

    // Start polling segment info
    fetchInfo(sessionId);
    infoTimerRef.current = setInterval(() => fetchInfo(sessionId), 2000);

    return () => {
      cleanup();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  /**
   * Track video time and play/pause state
   */
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const onTimeUpdate = () => setCurrentTime(video.currentTime);
    const onPlay = () => setPlaying(true);
    const onPause = () => setPlaying(false);

    video.addEventListener("timeupdate", onTimeUpdate);
    video.addEventListener("play", onPlay);
    video.addEventListener("pause", onPause);

    return () => {
      video.removeEventListener("timeupdate", onTimeUpdate);
      video.removeEventListener("play", onPlay);
      video.removeEventListener("pause", onPause);
    };
  }, []);

  /**
   * Stop polling when session is no longer running
   */
  useEffect(() => {
    if (sessionStatus !== "running" && infoTimerRef.current) {
      clearInterval(infoTimerRef.current);
      infoTimerRef.current = null;
    }
  }, [sessionStatus]);

  /**
   * Clean up HLS.js instance and info polling
   */
  function cleanup() {
    if (hlsRef.current) {
      hlsRef.current.destroy();
      hlsRef.current = null;
    }
    if (infoTimerRef.current) {
      clearInterval(infoTimerRef.current);
      infoTimerRef.current = null;
    }
    const video = videoRef.current;
    if (video) {
      video.removeAttribute("src");
      video.load();
    }
  }

  /**
   * Seek within the available range
   */
  const seekTo = useCallback((time: number) => {
    const video = videoRef.current;
    if (!video) return;
    video.currentTime = time;
  }, []);

  /**
   * Toggle play/pause
   */
  const togglePlay = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) {
      video.play().catch(() => {});
    } else {
      video.pause();
    }
  }, []);

  return {
    videoRef,
    loaded,
    error,
    playing,
    currentTime,
    totalDuration,
    availableDuration,
    segmentCount,
    sessionStatus,
    seekTo,
    togglePlay,
  };
}
