platform :macos, '10.15'
use_frameworks!

target 'mks-multiplatform-iptv' do
  # VLCKit for macOS (fallback player)
  # Note: KSPlayer is installed via SPM for all platforms
  pod 'VLCKit', '~> 3.7.0'
end

# iOS and tvOS use MobileVLCKit-SPM via Swift Package Manager:
# https://github.com/MobileVLCKit-SPM/MobileVLCKit-SPM

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end