platform :macos, '10.15'
use_frameworks!

target 'mks-multiplatform-iptv' do
  # VLCKit for macOS
  pod 'VLCKit', '~> 3.6.0'
  
  # Other dependencies (if any)
  # pod 'Alamofire', '~> 5.7'
  # pod 'SwiftyJSON', '~> 4.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end