# GitHub Pages Configuration
title: "MKS-IPTV-App"
description: "Native multiplatform IPTV client built with Swift 6"
url: "https://MKS2508.github.io"
baseurl: "/MKS-IPTV-App"

# Theme - Hacker theme for terminal/cyberpunk aesthetic


plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - download.md
  - installation.md
  - screenshots.md

# Social
github_username: MKS2508

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: assets/css
  style: compressed

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - build/
  - mks-multiplatform-iptv/
  - mks-multiplataforma-tvos-iptv/
  - .gitignore
  - vendor/

# Include
include:
  - imgs/